export const db = {}
export const auth = {}
export const rtdb = {}

export const collection = jest.fn()
export const doc = jest.fn()
export const addDoc = jest.fn()
export const setDoc = jest.fn()
export const updateDoc = jest.fn()
export const deleteDoc = jest.fn()
export const getDoc = jest.fn()
export const getDocs = jest.fn()
export const onSnapshot = jest.fn()
export const query = jest.fn()
export const where = jest.fn()
export const orderBy = jest.fn()
export const limit = jest.fn()
export const serverTimestamp = jest.fn(() => new Date())
export const Timestamp = { fromDate: jest.fn() }
export const arrayUnion = jest.fn()
export const arrayRemove = jest.fn()
export const ref = jest.fn()
export const set = jest.fn()
export const onValue = jest.fn()
export const onDisconnect = jest.fn(() => ({ set: jest.fn() }))
export const signInWithPopup = jest.fn()
export const signInWithEmailAndPassword = jest.fn()
export const createUserWithEmailAndPassword = jest.fn()
export const onAuthStateChanged = jest.fn()
export const signOut = jest.fn()
export const updatePassword = jest.fn()
export const sendPasswordResetEmail = jest.fn()
export const sendEmailVerification = jest.fn()
export const deleteUser = jest.fn()
export const reload = jest.fn()
export const GoogleAuthProvider = jest.fn(() => ({ setCustomParameters: jest.fn() }))
export const getAuth = jest.fn(() => auth)
export const getFirestore = jest.fn(() => db)
export const getDatabase = jest.fn(() => rtdb)
export const initializeApp = jest.fn()
export const getApps = jest.fn(() => [])
export const getApp = jest.fn()
